springfox:
  documentation:
    swagger.v2.path: /api-docs

server:
  contextPath: /storelocator/1.0
  port: 8080

spring:
  jackson:
    date-format: com.oscon2018.tutorials.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false